### PR TITLE
Tilemap.loadString - Ingore negative values

### PR DESCRIPTION
**Pull request by SmileyJames2**
Tilemap.loadString ln 303
"Ogmo Editor" outputs -1 in it's string if a tile is not present, the tilemap class handles this poorly due to the uint conversion. Proposed change handles negative values by ignoring them and not adding a tile.

### CODE REVIEW

**Comment by zachwlewis** [comment]
Why not simplify the check right before?

``` actionscript
if (col[x] == '' || int(col[x]) <= 0) continue;
setTile(x, y, uint(col[x]));
```

**Comment by SmileyJames2** [comment]
That works well :)
Sorry bit of a noob, first ever commit on GitHub.

**Comment by zachwlewis** [comment]
It's no problem! Just make the change in a new commit on this branch, and it'll show up here!

**Comment by SmileyJames2** [comment]
Has that worked? Or do I need to make a pull request?

**Comment by zachwlewis** [comment]
Close, you need to make that change in the patch-1 branch, not the master branch.

**Comment by SmileyJames2** [comment]
Aha got it :)

**Comment by zachwlewis** [comment]
Looks good! :shipit:

**Comment by SmileyJames2** [comment]
Thank you very much for the merge and help :)

**Pull request merged**
