### PR TITLE
Update Tween.as in order to call the finish method.

### PR DESCRIPTION
**Pull request by iRaySpace**

### CODE REVIEW

**Comment by Draknek** [comment]
Hi, `finish()` is already called from `Tweener.updateTweens()`.

If you're encountering situations where `finish()` is not being called when you believe it should be, then please post a reproducible testcase so I can look into what's going on.

**Comment by iRaySpace** [comment]
It's my first time here so I don't know that thing. finish() wasn't called on Alarm which is the inherited from the Tween. Which doesn't make the whole Alarm work.

**Comment by zachwlewis** [comment]
@iRaySpace Do you have an example of your `Alarm` not working?

**Comment by iRaySpace** [comment]
@zachwlewis Here is the example that Alarm won't work.
https://www.dropbox.com/s/0qos6d3rs6d1yrn/SimpleWorld.as

**Comment by zachwlewis** [comment]
@iRaySpace I can't access Dropbox files from my work network. Could you throw it on [Gist](http://gist.github.com) or just put the code here?

**Comment by Draknek** [comment]
It's not very unintuitive perhaps, but Tweens need to be added to a Tweener in order to behave properly.

Here's an example: https://gist.github.com/Draknek/7364426

(Untested, but should work. Note that I'm calling `world.addTween()` instead of manually updating the tween.)

**Comment by zachwlewis** [comment]
> It's not very unintuitive perhaps, but Tweens need to be added to a Tweener in order to behave properly.

This is what I was going to check for.

**Comment by iRaySpace** [comment]
@Draknek Does it really need to be added on the Tweener? I mean, what if there are guns where recoiling speed differs, then you have to add so many Alarm Tweens on the Tweener unless it has its own timer.

**Comment by Draknek** [comment]
Lots of tweens on the same Tweener is not a problem, and wouldn't be any different to manually updating lots of tweens anyway.

Note that Entity is a Tweener as well as World, so if you have a tween which only affects one entity and you want to keep it self-enclosed you can do `entity.addTween()` instead of `world.addTween()`.

In any case, the code attached to this pull request does not solve any problems in normal tween use and potentially introduces problems with specialised tweens which override `Tween.update()`, so I'm closing this issue. Feel free to continue discussing the matter however.

**Pull request closed without merging**
