### PR TITLE
Fix Hitboxes in Masklists not showing in renderDebug and corrected value...

### PR DESCRIPTION
**Pull request by azrafe7**
...s in Masklists.update()

before vs after fix

Now the calc of the Entity Mask bounds in Masklist should be fixed, and Hitbox has it's own renderDebug() which is executed only if it's part of a Masklist - this avoids to draw the same rect twice.

### CODE REVIEW

**Comment by azrafe7** [comment]
Evoking @Draknek  @zachwlewis @Rolpege !?

Sorry to bother, but haven't had any response to this and the other PR yet. Really there's no problem if they cannot be accepted, but a comment would be greatly appreciated.

Thanks ;D

**Comment by zachwlewis** [comment]
I'll take a look shortly.

**Comment by zachwlewis** [comment]
Looks good to me. :shipit:

**Comment by azrafe7** [comment]
\o/

**Pull request merged**
