### PR TITLE
abstracting Stage to allow for social network or portal submissions of FlashPunk games

### PR DESCRIPTION
**Pull request by erikyuzwa**
FP and Engine both bind to Stage during initialization which can interfere with website and social network API's that need to do the same.

FP.stage is modified to DisplayObject to allow for you to pass in a given DisplayObject into the Engine constructor. I made it an optional parameter in order to preserve existing FlashPunk games and to avoid the community chasing me with pitchforks.

Note that this @CaffeineViking deserves all the praise and glory if this fix helps you out. All I've done is abstract it into a pull request for the rest of the community.

(reference: http://dev.playvue.com/2013/07/using-root-instead-of-stage-in-flashpunk-haxepunk/)

### CODE REVIEW

**Comment by Draknek** [comment]
This change breaks backwards compatibility, so I'm not going to merge it.

FP.stage needs to remain as type Stage, so that games that _do_ want to access the stage (and there are a lot of them) can.

My proposed way of making games compatible with loading in a parent SWF requires no code changes (to FlashPunk):

Override `Engine.setStageProperties()` with an empty function.

As far as I can tell, this should be sufficient to resolve all problems: FlashPunk never adds any children to FP.stage, it just attaches event listeners (which should be fine). Let me know if I'm incorrect here!

**Comment by zachwlewis** [comment]
Would this be something to consider rolling in for the next major version?

**Comment by Draknek** [comment]
TBH if the only problem here is "FlashPunk sets some properties of the stage in an easily preventable manner" then I don't see the need to change anything in a future version, no.

Seems like appeasing a very small group (people who want to embed their game within another SWF) at the cost of the needs of a larger group (people using FlashPunk+AIR who need access to the stage and find the current behaviour useful).

**Comment by zachwlewis** [comment]
@erikyuzwa How would this change affect `Input`? It uses `stage` event listeners to determine keypresses. Would a `DisplayObject` on a `Stage` still receive these events?

@Draknek The constructor for `Engine` accepts any `DisplayObject` to be the "stage," so users who don't want to embed it, or who need the actual stage could just pass it in.

The ability to compartmentalize the game (allowing a user to move it around, flip it, stretch it, _et cetera_ with simple property changes) would be pretty handy and could help people to do more creative things with the game once they're unbound from the constraints of the game. Food for thought.

**Comment by Draknek** [comment]
@zachwlewis It doesn't need anything passed to the constructor though! The only thing that the presence of that parameter does in the above code, is to toggle whether `setStageProperties()` is called. It might as well be a boolean...

**Comment by erikyuzwa** [comment]
I'm pretty cognizant of the fact that it's making such a core change, so I can understand any trepidation even if the proposed solution appears to handle both cases properly (those who wish to keep FP "vanilla" and those who wish to drop it in somewhere).

At the very least, the pull exists for those who wish to take their FP game to a social game site. Does github allow "eternal" pull requests? :)

@zachwlewis obviously I'm still testing it out, but I haven't seen any evidence of Input events dropping off or being missed.

Also from official Adobe documentation, it looks like DisplayObject was introduced in Flash 9, so I'm not sure what the minimum support level of FlashPunk is targeting.

**Comment by zachwlewis** [comment]
A FlashPunk developer can close this pull request at any time; however, you can pull from the FlashPunk repo into your own, so you can simply maintain a repo with the change as long as you'd wish. 
—

**Comment by erikyuzwa** [comment]
thanks @zachwlewis , I'll just close off this request then and keep the mod'd version in my public repo.

**Comment by zachwlewis** [comment]
Sounds good! Don't forget to pull changes from this branch to keep yours up to date!
—

**Comment by erikyuzwa** [comment]
aye will do.

**Pull request closed without merging**
