### PR TITLE
Grid on grid collision not implemented

### PR DESCRIPTION
**Pull request by noonat**
Grid on grid collision is currently not implemented.

Reference topic:

http://flashpunk.net/forums/index.php?topic=1566.0

### CODE REVIEW

**Comment by Draknek** [comment]
Bug: http://www.draknek.org/misc/grid-grid-bug.png

Code: https://gist.github.com/1143292

For each tile I think you need to check all four corners.

**Comment by noonat** [comment]
Crap, I thought I got all the edge cases. Hmm, I will dig into this.

**Comment by noonat** [comment]
Yep, checking the corners was the right idea! Fixed: https://github.com/noonat/FlashPunk/commit/15c865406fcd126b27e51b18de85158efb5296bb

Note that there was also a bug where brow/bcol were subtracting this._x/_y instead of other._x/_y.

**Comment by Draknek** [comment]
Lovely. :)

In future can I cheekily request feature branches based off my master? Didn't appreciate just how useful they are until last night when I had to do some conflict resolution on changes I was expecting could be automatically merged.

**Comment by noonat** [comment]
Yep, I was thinking the same thing with this commit, haha.

**Comment by Draknek** [comment]
Another bug: http://www.draknek.org/misc/grid-grid-bug2.png https://gist.github.com/1143292

Seems to happen when the smaller grid is to the left of the larger grid.

**Comment by noonat** [comment]
Haha, I swear I _have_ been testing this! So, the bug: the top-left of the overlapping rect was in the middle of a tile for the smallest tile grid. This meant that checking corners was checking up to four different tiles in the small grid.

I am now extending the overlapping rect to the top and left to snap it to the tile grid for the smallest tile. I _think_ that's the right way to fix it? Am I crazy?

As requested, I've created a feature branch against your master for all of the grid grid work and opened a pull request for it.

**Comment by Draknek** [comment]
I wasn't entirely sure why it was happening, but that explanation sounds about right. Did some more tests, it all looks good.

Merged in now. Thanks again!

**Pull request merged**
