### PR TITLE
Text change font

### PR DESCRIPTION
**Pull request by sxd1140**

### CODE REVIEW

**Comment by zachwlewis** [comment]
Can you explain what this change fixes?

**Comment by sxd1140** [comment]
must set `embedFonts` to false if need change the default font

move `embedFonts` in `updateTextBuffer()`

it works

`new Text('x', 0, 0, {font:'Impact'});`
and
`text.font = 'Impact';`

**Comment by zachwlewis** [comment]
Sounds good.

:shipit:

**Comment by Draknek** [comment]
Argh, this does not do what you want it to do! I have reverted the commit.

@sxd1140 You always want to embed the font you are using, otherwise players on other computers may or may not see the correct font. You can do that with the following code:

`[Embed(source = 'path/to/Impact.ttf', embedAsCFF="false", fontFamily = 'Impact')]
public static const FONT:Class;`

(You should also check that you have the right to use the fonts you use, but that's another issue)

**Comment by sxd1140** [comment]
i know what you said
unfortunately sometime need use device font not embed
some non-englisth font is very big

most computers have some common font

**Comment by zachwlewis** [comment]
@sxd1140 Just let users know the download will take time due to IME fonts.

**Comment by sxd1140** [comment]
whatever

i like embed font if all fonts just like english font size

**Comment by azrafe7** [comment]
About using device fonts in FlashPunk:
http://developers.useflashpunk.net/t/using-devices-fonts-in-flashpunk/898

**Pull request merged**
