### PR TITLE
Bitmap cache should use Dictionary not Object (renamed, was: Clear cache)

### PR DESCRIPTION
**Pull request by BlckKnght**
This new method should be helpful for people to troubleshoot memory leak issues, as it lets them clear out the cache of BitmapData instances that's maintained by the getBitmap() method.

I'm not sure it's a great thing for games to use in production, but even if it's being misused it probably won't hurt much.

### CODE REVIEW

**Comment by noonat** [comment]
Related: that should probably be a Dictionary instead of an object.

**Comment by BlckKnght** [comment]
Hmm, I suppose it could be, but since the keys are explicitly converted to strings already it doesn't matter much.

**Comment by noonat** [comment]
Object lookup has side effects (both in operation and performance). It's a standard ECMAScript object, which means when you do obj["foo"], it searches up the prototype chain. It also means you can get interference from the default properties on the Object prototype.

Dictionary, on the other hand, is O(n) lookup and will never collide with prototype keys.

**Comment by BlckKnght** [comment]
Whoops, I didn't mean to close this request. I must have clicked on the wrong button.

**Comment by BlckKnght** [comment]
Ok, it seems any comment I make closes the request. Crazy....

**Comment by Draknek** [comment]
I've pulled in this change, but intend to make the Object to Dictionary change so won't close the issue.

**Comment by djcsdy** [comment]
djcsdy@d0e7462 changes the `Object` to `Dictionary`. It’s tested and working properly.

You can pull from my branch to get some other bits of superficial cleanup, if you want.

**Comment by Draknek** [comment]
Awesome, thanks a lot!

**Pull request closed without merging**
