### PR TITLE
Added clearSave function to Data class.

### PR DESCRIPTION
**Pull request by mikeevmm**
This would be particularly useful either for resetting the game or to erase wrongly saved values.

### CODE REVIEW

**Comment by jacobalbano** [comment]
I'd personally call it `clear()` instead of `clearSave()`, for consistency.

~~Also, being as I'm unfamiliar with the inner workings of this class, why does the new function clear `_shared` instead of `_data`? It seems to use `_data` everywhere else.~~ Never mind, now realizing that one is a SharedObject and one is an Object.

**Comment by zachwlewis** [comment]
I'm a fan of `clear()` as well. I hope the author pops back by to answer your question.

**Comment by mikeevmm** [comment]
I'm here, but Jacob seems to have answered himself?

**Comment by AbelToy** [comment]
This looks fine to me, merging!

**Comment by jacobalbano** [comment]
The only other suggestion I have is that `clear()` not take a parameter. Since all of the read/write operations assume an opened SharedObject already, it feels strange to me to specify the file to clear as a parameter, especially since `clear()` currently calls `Data.load()` anyway.

**Comment by jacobalbano** [comment]
@Rolpege I was in the middle of writing a comment when you merged, haha. Could you take a look at my suggestion if you missed it?

**Comment by AbelToy** [comment]
My fault! Yes, I agree. `clear()` should probably be only `_shared.clear()`.

Also, maybe flushing after clearing would be a good idea?

**Comment by jacobalbano** [comment]
I'm torn about that...it seems like the logical progression, but I feel like there should be a way to clear data without also saving it. Since the save/flush step already exists in a separate function, I feel like it would be best if saving was left as its own discrete step and not implied by the clear step.

**Comment by AbelToy** [comment]
Yeah, probably.

So, want to add to this pull request or how do we do it? :D

**Pull request merged**
